/** @format */

[
  { fieldName: "patientType", label: "Patient Type", inputTypeId: 3 },
  { fieldName: "patientId", label: "Patient Id", inputTypeId: 1 },
  { fieldName: "patientName", label: "Patient Name", inputTypeId: 1 },
  {
    fieldName: "patientNameAbbreviation",
    label: "Patient Name",
    inputTypeId: 3,
  },
  { fieldName: "gender", label: "Gender", inputTypeId: 7 },
  { fieldName: "address", label: "Address", inputTypeId: 1 },
  { fieldName: "district", label: "District", inputTypeId: 1 },
  { fieldName: "adharNumber", label: "Adhar Number", inputTypeId: 1 },
  { fieldName: "doctorName", label: "Doctor Name", inputTypeId: 1 },
  { fieldName: "sendSms", label: "Send Result via SMS", inputTypeId: 8 },
  { fieldName: "labCode", label: "Lab Code", inputTypeId: 1 },
  { fieldName: "age", label: "Age", inputTypeId: "4" },
  { fieldName: "email", label: "Email", inputTypeId: 1 },
  { fieldName: "city", label: "City", inputTypeId: 1 },
  { fieldName: "state", label: "State", inputTypeId: 1 },
  { fieldName: "srf", label: "SRF", inputTypeId: 1 },
  { fieldName: "isRegister", label: "Is Register", inputTypeId: 8 },
  { fieldName: "homeCollection", label: "Home Collection", inputTypeId: 8 },
  { fieldName: "membershipType", label: "Membership Type", inputTypeId: 3 },
  {
    fieldName: "registrationDate",
    label: "Registration Date",
    inputTypeId: 2,
  },
  { fieldName: "dateOfBirth", label: "Date of Birth", inputTypeId: 2 },
  { fieldName: "collectionDate", label: "Collection Date", inputTypeId: 2 },
  { fieldName: "mobileNumber", label: "Mobile Number", inputTypeId: 1 },
  {
    fieldName: "collectionCenter",
    label: "Collection Center",
    inputTypeId: 1,
  },
  { fieldName: "pinCode", label: "Pin Code", inputTypeId: 1 },
  { fieldName: "nationality", label: "Nationality", inputTypeId: 1 },
  { fieldName: "referredDoctor", label: "Referred Doctor", inputTypeId: 1 },
  { fieldName: "collectionBoy", label: "Collection Boy", inputTypeId: 1 },
  { fieldName: "paymentMethod", label: "Payment Method", inputTypeId: 7 },
  { fieldName: "submit", label: "Submit", inputTypeId: 6 },
  { fieldName: "cancel", label: "Cancel", inputTypeId: 6 },
];
